# Generated by Django 3.2.5 on 2021-07-30 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Textapp', '0016_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
