# Generated by Django 3.2.5 on 2021-08-04 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Textapp', '0018_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='full_content',
        ),
    ]
